# permissions for end users to view constraintdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraintdefinition-viewer-role
rules:
- apiGroups:
  - kuberdep.io
  resources:
  - constraintdefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberdep.io
  resources:
  - constraintdefinitions/status
  verbs:
  - get
