# permissions for end users to edit constraintdefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraintdefinition-editor-role
rules:
- apiGroups:
  - kuberdep.io
  resources:
  - constraintdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberdep.io
  resources:
  - constraintdefinitions/status
  verbs:
  - get
