# permissions for end users to edit entities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: entity-editor-role
rules:
- apiGroups:
  - kuberdep.io
  resources:
  - entities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberdep.io
  resources:
  - entities/status
  verbs:
  - get
