# permissions for end users to edit problems.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: problem-editor-role
rules:
- apiGroups:
  - kuberdep.io
  resources:
  - problems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberdep.io
  resources:
  - problems/status
  verbs:
  - get
