# permissions for end users to edit resolutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resolution-editor-role
rules:
- apiGroups:
  - kuberdep.io
  resources:
  - resolutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberdep.io
  resources:
  - resolutions/status
  verbs:
  - get
