# permissions for end users to view resolutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resolution-viewer-role
rules:
- apiGroups:
  - kuberdep.io
  resources:
  - resolutions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberdep.io
  resources:
  - resolutions/status
  verbs:
  - get
